#!/bin/bash

# Update package manager
sudo apt-get update

# Install Apache
sudo apt-get install -y apache2

# Ask for MySQL version
echo "Which version of MySQL do you want to install? (e.g. 'mysql-server-5.7')"
read mysql_version

# Install MySQL
sudo apt-get install -y "$mysql_version"

# Ask for PHP version
echo "Which version of PHP do you want to install? (e.g. 'php7.4')"
read php_version

# Install PHP
sudo apt-get install -y "$php_version" libapache2-mod-"$php_version" "$php_version"-mysql

# Restart Apache to apply changes
sudo service apache2 restart
